version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - API_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - JWT_SECRET=secret
      - JWT_REFRESH_SECRET=refresh_secret
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
